project_id: 726995
preserve_hierarchy: true
files:
  - source: config/locales/en.yml
    translation: config/locales/%two_letters_code%.%file_extension%
  - source: config/locales/*.en.yml
    translation: config/locales/%original_file_name%.%two_letters_code%.%file_extension%
    translation_replace:
      ".en.yml": ""
